--- # AT MODULE 
- hosts: apache-web-client
  user: ansible
  sudo: no
  connection: ssh
  gather_facts: no
  tasks:
    - name: Example of a future command with the AT module
      at: command="ls -la /var/log > /home/ansible/at.log" count=1 units=minutes 
