--- # COMMAND MODULE EXAMPLE
- hosts: ubuntu-server
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Running the shell script
      command: /home/ansible/testing/test.sh
      args:
        chdir: /home/ansible/testing
