--- # Ansible Cron Module Example 
- hosts: apache-web-client
  user: ansible
  sudo: no #if Yes will create the cron job under Root User
  connection: ssh
  gather_facts: no
  tasks: 
   - name: Create Cron job for Ansible user in the Remote host
     cron: name="Listing  Dir" minute="3" job="ls -la /home/ansible > /home/ansible/cronjob.output"
