--- ## Get_url ANsible Module
- hosts: local-host-ansible-core
  sudo: yes
  user: ansible
  connection: ssh 
  gather_facts: no
  tasks: 
   - name: Download RemoteDir from web server
     get_url: url=http://192.168.245.165/mina-Downloads dest=/home/ansible/mina-Downloads/ mode=0777
