--- # Pause Module Example
- hosts: apache-web-client
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: install httpd pkg 
     yum: name=httpd state=installed
   - name: pausing till user verificaion
     pause:
      prompt: verify the installation to proceed...
        ## seconds: 10  waiting for 10 seconds to proceed
   - name: installing the lynx pkg
     yum: name=lynx state=installed
     
