--- ## Selinux-Module-Example
- hosts: apache-web-client
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
   - name: changing the Selinux mode to permissive
     selinux: policy=targeted state=permissive #change the default and current mode
