--- ### set_fact module Example
- hosts: apache-web-client
  user: ansible
  sudo: yes
  connection: ssh 
  gather_facts: no
  vars:
   ansible_playbook: 2.5.1
  tasks: 
   - name: variables Display and facts
     set_fact: singlefact=something
   - debug: msg={{ ansible_playbook }}
   - debug: msg={{ singlefact }}

