# playbook to install lynx app on apache-web-client
- hosts: apache-web-client
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars: 
  vars_prompt: 
   - name: "pkg_name"
     prompt: enter the desired package name
  tasks:
   - name: install desired app {{ pkg_name }}
     action: yum name={{ pkg_name }} state=installed update_cache=yes

