--- # translation from outline to playBook
## target-section
- hosts: apache-web-client
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
### Task-Section
  tasks:
    - name: date/time stamp for when the playbook starts
      command: /usr/bin/date 
      register: timestart
    - debug: var=timestart

    - name: install apache web server 
      yum: pkg=httpd state=installed 
      notify: restart httpd service

    #- name: verify the website is running 
    #  command: sudo systemctl status httpd
    #  register: output
    #- debug: var=output

    - name: install client software lynx
      yum: pkg=lynx state=installed

    - name: log all the packages installed on the system 
      command: yum list installed
      register: listpkgs
    - debug: var=listpkgs 

    - name: date/time stamp for when the playbook ends
      command: /usr/bin/date
      register: timeend
    - debug: var=timeend
  handlers:
    - name: restart httpd service
      service: name=httpd state=restarted
 
